"""Layer rows for Glorious Engrammer."""

from __future__ import annotations

from typing import Dict, Tuple

from glove80.layouts.layers import Token

LayerRows = Tuple[Tuple[Token, ...], ...]

LAYER_ROWS: Dict[str, LayerRows] = {
    "Enthium": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "Z",
            "Y",
            "U",
            "O",
            "SEMI",
            "Q",
            "L",
        ),
        (
            "D",
            "P",
            "X",
            "&none",
            "W",
            ("Custom", "&LeftPinky (C, LAYER_Enthium)"),
            ("Custom", "&LeftRingy (I, LAYER_Enthium)"),
            ("Custom", "&LeftMiddy (E, LAYER_Enthium)"),
            ("Custom", "&LeftIndex (A, LAYER_Enthium)"),
            "COMMA",
        ),
        (
            "K",
            ("Custom", "&RightIndex (H, LAYER_Enthium)"),
            ("Custom", "&RightMiddy (T, LAYER_Enthium)"),
            ("Custom", "&RightRingy (N, LAYER_Enthium)"),
            ("Custom", "&RightPinky (S, LAYER_Enthium)"),
            "F",
            ("Custom", "&mo LAYER_Lower"),
            "SQT",
            "MINUS",
            "EQUAL",
        ),
        (
            "DOT",
            "FSLH",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "J",
            "M",
        ),
        (
            "G",
            "B",
            "V",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor SPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number TAB"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&thumb LAYER_Typing DELETE"),
            ("Custom", "&thumb LAYER_Mouse BACKSPACE"),
            ("Custom", "&space LAYER_Symbol R"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "Engrammer": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "B",
            "Y",
            "O",
            "U",
            "SQT",
            "SEMI",
            "L",
        ),
        (
            "D",
            "W",
            "V",
            "Z",
            "EQUAL",
            ("Custom", "&LeftPinky (C, LAYER_Engrammer)"),
            ("Custom", "&LeftRingy (I, LAYER_Engrammer)"),
            ("Custom", "&LeftMiddy (E, LAYER_Engrammer)"),
            ("Custom", "&LeftIndex (A, LAYER_Engrammer)"),
            "COMMA",
        ),
        (
            "DOT",
            ("Custom", "&RightIndex (H, LAYER_Engrammer)"),
            ("Custom", "&RightMiddy (T, LAYER_Engrammer)"),
            ("Custom", "&RightRingy (S, LAYER_Engrammer)"),
            ("Custom", "&RightPinky (N, LAYER_Engrammer)"),
            "Q",
            ("Custom", "&mo LAYER_Lower"),
            "G",
            "X",
            "J",
        ),
        (
            "K",
            "MINUS",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "FSLH",
            "R",
        ),
        (
            "M",
            "F",
            "P",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "Engram": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            ("Custom", "&engram_N1"),
            ("Custom", "&engram_N2"),
            ("Custom", "&engram_N3"),
            ("Custom", "&engram_N4"),
            ("Custom", "&engram_N5"),
            ("Custom", "&engram_N6"),
            ("Custom", "&engram_N7"),
            ("Custom", "&engram_N8"),
            ("Custom", "&engram_N9"),
        ),
        (
            ("Custom", "&engram_N0"),
            "&none",
            "&none",
            "B",
            "Y",
            "O",
            "U",
            ("Custom", "&engram_SQT"),
            ("Custom", "&engram_DQT"),
            "L",
        ),
        (
            "D",
            "W",
            "V",
            "Z",
            ("Custom", "&engram_HASH"),
            ("Custom", "&LeftPinky (C, LAYER_Engram)"),
            ("Custom", "&LeftRingy (I, LAYER_Engram)"),
            ("Custom", "&LeftMiddy (E, LAYER_Engram)"),
            ("Custom", "&LeftIndex (A, LAYER_Engram)"),
            ("Custom", "&engram_COMMA"),
        ),
        (
            ("Custom", "&engram_DOT"),
            ("Custom", "&RightIndex (H, LAYER_Engram)"),
            ("Custom", "&RightMiddy (T, LAYER_Engram)"),
            ("Custom", "&RightRingy (S, LAYER_Engram)"),
            ("Custom", "&RightPinky (N, LAYER_Engram)"),
            "Q",
            ("Custom", "&mo LAYER_Lower"),
            "G",
            "X",
            "J",
        ),
        (
            "K",
            "MINUS",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            ("Custom", "&engram_QMARK"),
            "R",
        ),
        (
            "M",
            "F",
            "P",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            ("Custom", "&engram_FSLH"),
            "LBKT",
            "RBKT",
            ("Custom", "&thumb_engram_AT LAYER_Emoji 0"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "Dvorak": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "SQT",
            "COMMA",
            "DOT",
            "P",
            "Y",
            "F",
            "G",
        ),
        (
            "C",
            "R",
            "L",
            "SLASH",
            "EQUAL",
            ("Custom", "&LeftPinky (A, LAYER_Dvorak)"),
            ("Custom", "&LeftRingy (O, LAYER_Dvorak)"),
            ("Custom", "&LeftMiddy (E, LAYER_Dvorak)"),
            ("Custom", "&LeftIndex (U, LAYER_Dvorak)"),
            "I",
        ),
        (
            "D",
            ("Custom", "&RightIndex (H, LAYER_Dvorak)"),
            ("Custom", "&RightMiddy (T, LAYER_Dvorak)"),
            ("Custom", "&RightRingy (N, LAYER_Dvorak)"),
            ("Custom", "&RightPinky (S, LAYER_Dvorak)"),
            "MINUS",
            ("Custom", "&mo LAYER_Lower"),
            "SEMI",
            "Q",
            "J",
        ),
        (
            "K",
            "X",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "B",
            "M",
        ),
        (
            "W",
            "V",
            "Z",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "Colemak": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "Q",
            "W",
            "F",
            "P",
            "G",
            "J",
            "L",
        ),
        (
            "U",
            "Y",
            "SEMI",
            "MINUS",
            "EQUAL",
            ("Custom", "&LeftPinky (A, LAYER_Colemak)"),
            ("Custom", "&LeftRingy (R, LAYER_Colemak)"),
            ("Custom", "&LeftMiddy (S, LAYER_Colemak)"),
            ("Custom", "&LeftIndex (T, LAYER_Colemak)"),
            "D",
        ),
        (
            "H",
            ("Custom", "&RightIndex (N, LAYER_Colemak)"),
            ("Custom", "&RightMiddy (E, LAYER_Colemak)"),
            ("Custom", "&RightRingy (I, LAYER_Colemak)"),
            ("Custom", "&RightPinky (O, LAYER_Colemak)"),
            "SQT",
            ("Custom", "&mo LAYER_Lower"),
            "Z",
            "X",
            "C",
        ),
        (
            "V",
            "B",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "K",
            "M",
        ),
        (
            "COMMA",
            "DOT",
            "FSLH",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&crumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "QWERTY": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "Q",
            "W",
            "E",
            "R",
            "T",
            "Y",
            "U",
        ),
        (
            "I",
            "O",
            "P",
            "MINUS",
            "EQUAL",
            ("Custom", "&LeftPinky (A, LAYER_QWERTY)"),
            ("Custom", "&LeftRingy (S, LAYER_QWERTY)"),
            ("Custom", "&LeftMiddy (D, LAYER_QWERTY)"),
            ("Custom", "&LeftIndex (F, LAYER_QWERTY)"),
            "G",
        ),
        (
            "H",
            ("Custom", "&RightIndex (J, LAYER_QWERTY)"),
            ("Custom", "&RightMiddy (K, LAYER_QWERTY)"),
            ("Custom", "&RightRingy (L, LAYER_QWERTY)"),
            ("Custom", "&RightPinky (SEMI, LAYER_QWERTY)"),
            "SQT",
            ("Custom", "&mo LAYER_Lower"),
            "Z",
            "X",
            "C",
        ),
        (
            "V",
            "B",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "N",
            "M",
        ),
        (
            "COMMA",
            "DOT",
            "FSLH",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "ColemakDH": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "&none",
            "&none",
            "Q",
            "W",
            "F",
            "P",
            "B",
            "J",
            "L",
        ),
        (
            "U",
            "Y",
            "SEMI",
            "MINUS",
            "EQUAL",
            ("Custom", "&LeftPinky (A, LAYER_ColemakDH)"),
            ("Custom", "&LeftRingy (R, LAYER_ColemakDH)"),
            ("Custom", "&LeftMiddy (S, LAYER_ColemakDH)"),
            ("Custom", "&LeftIndex (T, LAYER_ColemakDH)"),
            "G",
        ),
        (
            "M",
            ("Custom", "&RightIndex (N, LAYER_ColemakDH)"),
            ("Custom", "&RightMiddy (E, LAYER_ColemakDH)"),
            ("Custom", "&RightRingy (I, LAYER_ColemakDH)"),
            ("Custom", "&RightPinky (O, LAYER_ColemakDH)"),
            "SQT",
            ("Custom", "&mo LAYER_Lower"),
            "Z",
            "X",
            "C",
        ),
        (
            "D",
            "V",
            ("Custom", "&thumb LAYER_Function ESC"),
            ("Custom", "&parang_left"),
            ("Custom", "&parang_right"),
            ("Custom", "&kp _HOME"),
            ("Custom", "&kp _END"),
            ("Custom", "&thumb LAYER_System ENTER"),
            "K",
            "H",
        ),
        (
            "COMMA",
            "DOT",
            "FSLH",
            ("Custom", "&mo LAYER_Lower"),
            "&magic",
            "GRAVE",
            "LBKT",
            "RBKT",
            ("Custom", "&thumb LAYER_Emoji BSLH"),
            ("Custom", "&thumb LAYER_Cursor BACKSPACE"),
        ),
        (
            ("Custom", "&thumb LAYER_Number DELETE"),
            ("Custom", "&thumb LAYER_Typing INSERT"),
            ("Custom", "&mo LAYER_Typing"),
            ("Custom", "&thumb LAYER_Mouse TAB"),
            ("Custom", "&space LAYER_Symbol SPACE"),
            ("Custom", "&thumb LAYER_World PAGE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            "PG_DN",
            "&magic",
        ),
    ),
    "Typing": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&kp LEFT_PINKY_KEY"),
            ("Custom", "&kp LEFT_RINGY_KEY"),
            ("Custom", "&kp LEFT_MIDDY_KEY"),
            ("Custom", "&kp LEFT_INDEX_KEY"),
            "&trans",
        ),
        (
            "&trans",
            ("Custom", "&kp RIGHT_INDEX_KEY"),
            ("Custom", "&kp RIGHT_MIDDY_KEY"),
            ("Custom", "&kp RIGHT_RINGY_KEY"),
            ("Custom", "&kp RIGHT_PINKY_KEY"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&kp KEY_LH_T1"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&kp KEY_RH_T1"),
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&kp KEY_LH_C2R6"),
            ("Custom", "&kp KEY_LH_T4"),
        ),
        (
            ("Custom", "&kp KEY_LH_T5"),
            ("Custom", "&kp KEY_LH_T6"),
            ("Custom", "&kp KEY_RH_T6"),
            ("Custom", "&kp KEY_RH_T5"),
            ("Custom", "&kp KEY_RH_T4"),
            ("Custom", "&kp KEY_RH_C2R6"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "LeftPinky": (
        (
            ("Custom", "&left_pinky_tap KEY_LH_C6R1"),
            ("Custom", "&left_pinky_tap KEY_LH_C5R1"),
            ("Custom", "&left_pinky_tap KEY_LH_C4R1"),
            ("Custom", "&left_pinky_tap KEY_LH_C3R1"),
            ("Custom", "&left_pinky_tap KEY_LH_C2R1"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            ("Custom", "&left_pinky_tap KEY_LH_C6R2"),
            ("Custom", "&left_pinky_tap KEY_LH_C5R2"),
            ("Custom", "&left_pinky_tap KEY_LH_C4R2"),
            ("Custom", "&left_pinky_tap KEY_LH_C3R2"),
            ("Custom", "&left_pinky_tap KEY_LH_C2R2"),
            ("Custom", "&left_pinky_tap KEY_LH_C1R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&left_pinky_tap KEY_LH_C6R3"),
            ("Custom", "&left_pinky_tap KEY_LH_C5R3"),
            ("Custom", "&left_pinky_tap KEY_LH_C4R3"),
            ("Custom", "&left_pinky_tap KEY_LH_C3R3"),
            ("Custom", "&left_pinky_tap KEY_LH_C2R3"),
            ("Custom", "&left_pinky_tap KEY_LH_C1R3"),
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_pinky_tap KEY_LH_C6R4"),
            "&none",
            ("Custom", "&LeftPinkyRingy"),
            ("Custom", "&LeftPinkyMiddy"),
            ("Custom", "&LeftPinkyIndex"),
            ("Custom", "&left_pinky_tap KEY_LH_C1R4"),
        ),
        (
            "&trans",
            ("Custom", "&kp RIGHT_INDEX_KEY"),
            ("Custom", "&kp RIGHT_MIDDY_KEY"),
            ("Custom", "&kp RIGHT_RINGY_KEY"),
            ("Custom", "&kp RIGHT_PINKY_KEY"),
            "&trans",
            "&trans",
            ("Custom", "&left_pinky_tap KEY_LH_C5R5"),
            ("Custom", "&left_pinky_tap KEY_LH_C4R5"),
            ("Custom", "&left_pinky_tap KEY_LH_C3R5"),
        ),
        (
            ("Custom", "&left_pinky_tap KEY_LH_C2R5"),
            ("Custom", "&left_pinky_tap KEY_LH_C1R5"),
            ("Custom", "&mo LAY_LH_T1"),
            ("Custom", "&left_pinky_tap KEY_LH_T2"),
            ("Custom", "&left_pinky_tap KEY_LH_T3"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_pinky_tap KEY_LH_C5R6"),
            ("Custom", "&left_pinky_tap KEY_LH_C4R6"),
            ("Custom", "&left_pinky_tap KEY_LH_C3R6"),
            ("Custom", "&mo LAY_LH_C2R6"),
            ("Custom", "&mo LAY_LH_T4"),
        ),
        (
            ("Custom", "&mo LAY_LH_T5"),
            ("Custom", "&mo LAY_LH_T6"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "LeftRingy": (
        (
            ("Custom", "&left_ringy_tap KEY_LH_C6R1"),
            ("Custom", "&left_ringy_tap KEY_LH_C5R1"),
            ("Custom", "&left_ringy_tap KEY_LH_C4R1"),
            ("Custom", "&left_ringy_tap KEY_LH_C3R1"),
            ("Custom", "&left_ringy_tap KEY_LH_C2R1"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            ("Custom", "&left_ringy_tap KEY_LH_C6R2"),
            ("Custom", "&left_ringy_tap KEY_LH_C5R2"),
            ("Custom", "&left_ringy_tap KEY_LH_C4R2"),
            ("Custom", "&left_ringy_tap KEY_LH_C3R2"),
            ("Custom", "&left_ringy_tap KEY_LH_C2R2"),
            ("Custom", "&left_ringy_tap KEY_LH_C1R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&left_ringy_tap KEY_LH_C6R3"),
            ("Custom", "&left_ringy_tap KEY_LH_C5R3"),
            ("Custom", "&left_ringy_tap KEY_LH_C4R3"),
            ("Custom", "&left_ringy_tap KEY_LH_C3R3"),
            ("Custom", "&left_ringy_tap KEY_LH_C2R3"),
            ("Custom", "&left_ringy_tap KEY_LH_C1R3"),
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_ringy_tap KEY_LH_C6R4"),
            ("Custom", "&LeftRingyPinky"),
            "&none",
            ("Custom", "&LeftRingyMiddy"),
            ("Custom", "&LeftRingyIndex"),
            ("Custom", "&left_ringy_tap KEY_LH_C1R4"),
        ),
        (
            "&trans",
            ("Custom", "&kp RIGHT_INDEX_KEY"),
            ("Custom", "&kp RIGHT_MIDDY_KEY"),
            ("Custom", "&kp RIGHT_RINGY_KEY"),
            ("Custom", "&kp RIGHT_PINKY_KEY"),
            "&trans",
            "&trans",
            ("Custom", "&left_ringy_tap KEY_LH_C5R5"),
            ("Custom", "&left_ringy_tap KEY_LH_C4R5"),
            ("Custom", "&left_ringy_tap KEY_LH_C3R5"),
        ),
        (
            ("Custom", "&left_ringy_tap KEY_LH_C2R5"),
            ("Custom", "&left_ringy_tap KEY_LH_C1R5"),
            ("Custom", "&mo LAY_LH_T1"),
            ("Custom", "&left_ringy_tap KEY_LH_T2"),
            ("Custom", "&left_ringy_tap KEY_LH_T3"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_ringy_tap KEY_LH_C5R6"),
            ("Custom", "&left_ringy_tap KEY_LH_C4R6"),
            ("Custom", "&left_ringy_tap KEY_LH_C3R6"),
            ("Custom", "&mo LAY_LH_C2R6"),
            ("Custom", "&mo LAY_LH_T4"),
        ),
        (
            ("Custom", "&mo LAY_LH_T5"),
            ("Custom", "&mo LAY_LH_T6"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "LeftMiddy": (
        (
            ("Custom", "&left_middy_tap KEY_LH_C6R1"),
            ("Custom", "&left_middy_tap KEY_LH_C5R1"),
            ("Custom", "&left_middy_tap KEY_LH_C4R1"),
            ("Custom", "&left_middy_tap KEY_LH_C3R1"),
            ("Custom", "&left_middy_tap KEY_LH_C2R1"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            ("Custom", "&left_middy_tap KEY_LH_C6R2"),
            ("Custom", "&left_middy_tap KEY_LH_C5R2"),
            ("Custom", "&left_middy_tap KEY_LH_C4R2"),
            ("Custom", "&left_middy_tap KEY_LH_C3R2"),
            ("Custom", "&left_middy_tap KEY_LH_C2R2"),
            ("Custom", "&left_middy_tap KEY_LH_C1R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&left_middy_tap KEY_LH_C6R3"),
            ("Custom", "&left_middy_tap KEY_LH_C5R3"),
            ("Custom", "&left_middy_tap KEY_LH_C4R3"),
            ("Custom", "&left_middy_tap KEY_LH_C3R3"),
            ("Custom", "&left_middy_tap KEY_LH_C2R3"),
            ("Custom", "&left_middy_tap KEY_LH_C1R3"),
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_middy_tap KEY_LH_C6R4"),
            ("Custom", "&LeftMiddyPinky"),
            ("Custom", "&LeftMiddyRingy"),
            "&none",
            ("Custom", "&LeftMiddyIndex"),
            ("Custom", "&left_middy_tap KEY_LH_C1R4"),
        ),
        (
            "&trans",
            ("Custom", "&kp RIGHT_INDEX_KEY"),
            ("Custom", "&kp RIGHT_MIDDY_KEY"),
            ("Custom", "&kp RIGHT_RINGY_KEY"),
            ("Custom", "&kp RIGHT_PINKY_KEY"),
            "&trans",
            "&trans",
            ("Custom", "&left_middy_tap KEY_LH_C5R5"),
            ("Custom", "&left_middy_tap KEY_LH_C4R5"),
            ("Custom", "&left_middy_tap KEY_LH_C3R5"),
        ),
        (
            ("Custom", "&left_middy_tap KEY_LH_C2R5"),
            ("Custom", "&left_middy_tap KEY_LH_C1R5"),
            ("Custom", "&mo LAY_LH_T1"),
            ("Custom", "&left_middy_tap KEY_LH_T2"),
            ("Custom", "&left_middy_tap KEY_LH_T3"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_middy_tap KEY_LH_C5R6"),
            ("Custom", "&left_middy_tap KEY_LH_C4R6"),
            ("Custom", "&left_middy_tap KEY_LH_C3R6"),
            ("Custom", "&mo LAY_LH_C2R6"),
            ("Custom", "&mo LAY_LH_T4"),
        ),
        (
            ("Custom", "&mo LAY_LH_T5"),
            ("Custom", "&mo LAY_LH_T6"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "LeftIndex": (
        (
            ("Custom", "&left_index_tap KEY_LH_C6R1"),
            ("Custom", "&left_index_tap KEY_LH_C5R1"),
            ("Custom", "&left_index_tap KEY_LH_C4R1"),
            ("Custom", "&left_index_tap KEY_LH_C3R1"),
            ("Custom", "&left_index_tap KEY_LH_C2R1"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            ("Custom", "&left_index_tap KEY_LH_C6R2"),
            ("Custom", "&left_index_tap KEY_LH_C5R2"),
            ("Custom", "&left_index_tap KEY_LH_C4R2"),
            ("Custom", "&left_index_tap KEY_LH_C3R2"),
            ("Custom", "&left_index_tap KEY_LH_C2R2"),
            ("Custom", "&left_index_tap KEY_LH_C1R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&left_index_tap KEY_LH_C6R3"),
            ("Custom", "&left_index_tap KEY_LH_C5R3"),
            ("Custom", "&left_index_tap KEY_LH_C4R3"),
            ("Custom", "&left_index_tap KEY_LH_C3R3"),
            ("Custom", "&left_index_tap KEY_LH_C2R3"),
            ("Custom", "&left_index_tap KEY_LH_C1R3"),
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_index_tap KEY_LH_C6R4"),
            ("Custom", "&LeftIndexPinky"),
            ("Custom", "&LeftIndexRingy"),
            ("Custom", "&LeftIndexMiddy"),
            "&none",
            ("Custom", "&left_index_tap KEY_LH_C1R4"),
        ),
        (
            "&trans",
            ("Custom", "&kp RIGHT_INDEX_KEY"),
            ("Custom", "&kp RIGHT_MIDDY_KEY"),
            ("Custom", "&kp RIGHT_RINGY_KEY"),
            ("Custom", "&kp RIGHT_PINKY_KEY"),
            "&trans",
            "&trans",
            ("Custom", "&left_index_tap KEY_LH_C5R5"),
            ("Custom", "&left_index_tap KEY_LH_C4R5"),
            ("Custom", "&left_index_tap KEY_LH_C3R5"),
        ),
        (
            ("Custom", "&left_index_tap KEY_LH_C2R5"),
            ("Custom", "&left_index_tap KEY_LH_C1R5"),
            ("Custom", "&mo LAY_LH_T1"),
            ("Custom", "&left_index_tap KEY_LH_T2"),
            ("Custom", "&left_index_tap KEY_LH_T3"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&left_index_tap KEY_LH_C5R6"),
            ("Custom", "&left_index_tap KEY_LH_C4R6"),
            ("Custom", "&left_index_tap KEY_LH_C3R6"),
            ("Custom", "&mo LAY_LH_C2R6"),
            ("Custom", "&mo LAY_LH_T4"),
        ),
        (
            ("Custom", "&mo LAY_LH_T5"),
            ("Custom", "&mo LAY_LH_T6"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "RightPinky": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_pinky_tap KEY_RH_C2R1"),
            ("Custom", "&right_pinky_tap KEY_RH_C3R1"),
            ("Custom", "&right_pinky_tap KEY_RH_C4R1"),
            ("Custom", "&right_pinky_tap KEY_RH_C5R1"),
            ("Custom", "&right_pinky_tap KEY_RH_C6R1"),
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_pinky_tap KEY_RH_C1R2"),
            ("Custom", "&right_pinky_tap KEY_RH_C2R2"),
            ("Custom", "&right_pinky_tap KEY_RH_C3R2"),
            ("Custom", "&right_pinky_tap KEY_RH_C4R2"),
        ),
        (
            ("Custom", "&right_pinky_tap KEY_RH_C5R2"),
            ("Custom", "&right_pinky_tap KEY_RH_C6R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_pinky_tap KEY_RH_C1R3"),
            ("Custom", "&right_pinky_tap KEY_RH_C2R3"),
        ),
        (
            ("Custom", "&right_pinky_tap KEY_RH_C3R3"),
            ("Custom", "&right_pinky_tap KEY_RH_C4R3"),
            ("Custom", "&right_pinky_tap KEY_RH_C5R3"),
            ("Custom", "&right_pinky_tap KEY_RH_C6R3"),
            "&trans",
            ("Custom", "&kp LEFT_PINKY_KEY"),
            ("Custom", "&kp LEFT_RINGY_KEY"),
            ("Custom", "&kp LEFT_MIDDY_KEY"),
            ("Custom", "&kp LEFT_INDEX_KEY"),
            "&trans",
        ),
        (
            ("Custom", "&right_pinky_tap KEY_RH_C1R4"),
            ("Custom", "&RightPinkyIndex"),
            ("Custom", "&RightPinkyMiddy"),
            ("Custom", "&RightPinkyRingy"),
            "&none",
            ("Custom", "&right_pinky_tap KEY_RH_C6R4"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_pinky_tap KEY_RH_T3"),
            ("Custom", "&right_pinky_tap KEY_RH_T2"),
            ("Custom", "&mo LAY_RH_T1"),
            ("Custom", "&right_pinky_tap KEY_RH_C1R5"),
            ("Custom", "&right_pinky_tap KEY_RH_C2R5"),
        ),
        (
            ("Custom", "&right_pinky_tap KEY_RH_C3R5"),
            ("Custom", "&right_pinky_tap KEY_RH_C4R5"),
            ("Custom", "&right_pinky_tap KEY_RH_C5R5"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&mo LAY_RH_T6"),
            ("Custom", "&mo LAY_RH_T5"),
            ("Custom", "&mo LAY_RH_T4"),
            ("Custom", "&mo LAY_RH_C2R6"),
            ("Custom", "&right_pinky_tap KEY_RH_C3R6"),
            ("Custom", "&right_pinky_tap KEY_RH_C4R6"),
            ("Custom", "&right_pinky_tap KEY_RH_C5R6"),
            "&trans",
        ),
    ),
    "RightRingy": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_ringy_tap KEY_RH_C2R1"),
            ("Custom", "&right_ringy_tap KEY_RH_C3R1"),
            ("Custom", "&right_ringy_tap KEY_RH_C4R1"),
            ("Custom", "&right_ringy_tap KEY_RH_C5R1"),
            ("Custom", "&right_ringy_tap KEY_RH_C6R1"),
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_ringy_tap KEY_RH_C1R2"),
            ("Custom", "&right_ringy_tap KEY_RH_C2R2"),
            ("Custom", "&right_ringy_tap KEY_RH_C3R2"),
            ("Custom", "&right_ringy_tap KEY_RH_C4R2"),
        ),
        (
            ("Custom", "&right_ringy_tap KEY_RH_C5R2"),
            ("Custom", "&right_ringy_tap KEY_RH_C6R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_ringy_tap KEY_RH_C1R3"),
            ("Custom", "&right_ringy_tap KEY_RH_C2R3"),
        ),
        (
            ("Custom", "&right_ringy_tap KEY_RH_C3R3"),
            ("Custom", "&right_ringy_tap KEY_RH_C4R3"),
            ("Custom", "&right_ringy_tap KEY_RH_C5R3"),
            ("Custom", "&right_ringy_tap KEY_RH_C6R3"),
            "&trans",
            ("Custom", "&kp LEFT_PINKY_KEY"),
            ("Custom", "&kp LEFT_RINGY_KEY"),
            ("Custom", "&kp LEFT_MIDDY_KEY"),
            ("Custom", "&kp LEFT_INDEX_KEY"),
            "&trans",
        ),
        (
            ("Custom", "&right_ringy_tap KEY_RH_C1R4"),
            ("Custom", "&RightRingyIndex"),
            ("Custom", "&RightRingyMiddy"),
            "&none",
            ("Custom", "&RightRingyPinky"),
            ("Custom", "&right_ringy_tap KEY_RH_C6R4"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_ringy_tap KEY_RH_T3"),
            ("Custom", "&right_ringy_tap KEY_RH_T2"),
            ("Custom", "&mo LAY_RH_T1"),
            ("Custom", "&right_ringy_tap KEY_RH_C1R5"),
            ("Custom", "&right_ringy_tap KEY_RH_C2R5"),
        ),
        (
            ("Custom", "&right_ringy_tap KEY_RH_C3R5"),
            ("Custom", "&right_ringy_tap KEY_RH_C4R5"),
            ("Custom", "&right_ringy_tap KEY_RH_C5R5"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&mo LAY_RH_T6"),
            ("Custom", "&mo LAY_RH_T5"),
            ("Custom", "&mo LAY_RH_T4"),
            ("Custom", "&mo LAY_RH_C2R6"),
            ("Custom", "&right_ringy_tap KEY_RH_C3R6"),
            ("Custom", "&right_ringy_tap KEY_RH_C4R6"),
            ("Custom", "&right_ringy_tap KEY_RH_C5R6"),
            "&trans",
        ),
    ),
    "RightMiddy": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_middy_tap KEY_RH_C2R1"),
            ("Custom", "&right_middy_tap KEY_RH_C3R1"),
            ("Custom", "&right_middy_tap KEY_RH_C4R1"),
            ("Custom", "&right_middy_tap KEY_RH_C5R1"),
            ("Custom", "&right_middy_tap KEY_RH_C6R1"),
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_middy_tap KEY_RH_C1R2"),
            ("Custom", "&right_middy_tap KEY_RH_C2R2"),
            ("Custom", "&right_middy_tap KEY_RH_C3R2"),
            ("Custom", "&right_middy_tap KEY_RH_C4R2"),
        ),
        (
            ("Custom", "&right_middy_tap KEY_RH_C5R2"),
            ("Custom", "&right_middy_tap KEY_RH_C6R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_middy_tap KEY_RH_C1R3"),
            ("Custom", "&right_middy_tap KEY_RH_C2R3"),
        ),
        (
            ("Custom", "&right_middy_tap KEY_RH_C3R3"),
            ("Custom", "&right_middy_tap KEY_RH_C4R3"),
            ("Custom", "&right_middy_tap KEY_RH_C5R3"),
            ("Custom", "&right_middy_tap KEY_RH_C6R3"),
            "&trans",
            ("Custom", "&kp LEFT_PINKY_KEY"),
            ("Custom", "&kp LEFT_RINGY_KEY"),
            ("Custom", "&kp LEFT_MIDDY_KEY"),
            ("Custom", "&kp LEFT_INDEX_KEY"),
            "&trans",
        ),
        (
            ("Custom", "&right_middy_tap KEY_RH_C1R4"),
            ("Custom", "&RightMiddyIndex"),
            "&none",
            ("Custom", "&RightMiddyRingy"),
            ("Custom", "&RightMiddyPinky"),
            ("Custom", "&right_middy_tap KEY_RH_C6R4"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_middy_tap KEY_RH_T3"),
            ("Custom", "&right_middy_tap KEY_RH_T2"),
            ("Custom", "&mo LAY_RH_T1"),
            ("Custom", "&right_middy_tap KEY_RH_C1R5"),
            ("Custom", "&right_middy_tap KEY_RH_C2R5"),
        ),
        (
            ("Custom", "&right_middy_tap KEY_RH_C3R5"),
            ("Custom", "&right_middy_tap KEY_RH_C4R5"),
            ("Custom", "&right_middy_tap KEY_RH_C5R5"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&mo LAY_RH_T6"),
            ("Custom", "&mo LAY_RH_T5"),
            ("Custom", "&mo LAY_RH_T4"),
            ("Custom", "&mo LAY_RH_C2R6"),
            ("Custom", "&right_middy_tap KEY_RH_C3R6"),
            ("Custom", "&right_middy_tap KEY_RH_C4R6"),
            ("Custom", "&right_middy_tap KEY_RH_C5R6"),
            "&trans",
        ),
    ),
    "RightIndex": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_index_tap KEY_RH_C2R1"),
            ("Custom", "&right_index_tap KEY_RH_C3R1"),
            ("Custom", "&right_index_tap KEY_RH_C4R1"),
            ("Custom", "&right_index_tap KEY_RH_C5R1"),
            ("Custom", "&right_index_tap KEY_RH_C6R1"),
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_index_tap KEY_RH_C1R2"),
            ("Custom", "&right_index_tap KEY_RH_C2R2"),
            ("Custom", "&right_index_tap KEY_RH_C3R2"),
            ("Custom", "&right_index_tap KEY_RH_C4R2"),
        ),
        (
            ("Custom", "&right_index_tap KEY_RH_C5R2"),
            ("Custom", "&right_index_tap KEY_RH_C6R2"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_index_tap KEY_RH_C1R3"),
            ("Custom", "&right_index_tap KEY_RH_C2R3"),
        ),
        (
            ("Custom", "&right_index_tap KEY_RH_C3R3"),
            ("Custom", "&right_index_tap KEY_RH_C4R3"),
            ("Custom", "&right_index_tap KEY_RH_C5R3"),
            ("Custom", "&right_index_tap KEY_RH_C6R3"),
            "&trans",
            ("Custom", "&kp LEFT_PINKY_KEY"),
            ("Custom", "&kp LEFT_RINGY_KEY"),
            ("Custom", "&kp LEFT_MIDDY_KEY"),
            ("Custom", "&kp LEFT_INDEX_KEY"),
            "&trans",
        ),
        (
            ("Custom", "&right_index_tap KEY_RH_C1R4"),
            "&none",
            ("Custom", "&RightIndexMiddy"),
            ("Custom", "&RightIndexRingy"),
            ("Custom", "&RightIndexPinky"),
            ("Custom", "&right_index_tap KEY_RH_C6R4"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            ("Custom", "&right_index_tap KEY_RH_T3"),
            ("Custom", "&right_index_tap KEY_RH_T2"),
            ("Custom", "&mo LAY_RH_T1"),
            ("Custom", "&right_index_tap KEY_RH_C1R5"),
            ("Custom", "&right_index_tap KEY_RH_C2R5"),
        ),
        (
            ("Custom", "&right_index_tap KEY_RH_C3R5"),
            ("Custom", "&right_index_tap KEY_RH_C4R5"),
            ("Custom", "&right_index_tap KEY_RH_C5R5"),
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            ("Custom", "&mo LAY_RH_T6"),
            ("Custom", "&mo LAY_RH_T5"),
            ("Custom", "&mo LAY_RH_T4"),
            ("Custom", "&mo LAY_RH_C2R6"),
            ("Custom", "&right_index_tap KEY_RH_C3R6"),
            ("Custom", "&right_index_tap KEY_RH_C4R6"),
            ("Custom", "&right_index_tap KEY_RH_C5R6"),
            "&trans",
        ),
    ),
    "Cursor": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "ESC",
            "INS",
            ("&kp", ("LS", "TAB")),
            "DEL",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "RET",
            "SPACE",
            "TAB",
            "BSPC",
            ("Custom", "&kp _CUT"),
            ("Custom", "&kp _CUT"),
            ("&kp", ("LS", "TAB")),
        ),
        (
            ("Custom", "&kp _UNDO"),
            ("Custom", "&kp _REDO"),
            "TAB",
            "&none",
            ("&sk", "LSHFT"),
            ("Custom", "&kp LEFT_PINKY_MOD"),
            ("Custom", "&kp LEFT_RINGY_MOD"),
            ("Custom", "&kp LEFT_MIDDY_MOD"),
            ("Custom", "&kp LEFT_INDEX_MOD"),
            ("Custom", "&kp _COPY"),
        ),
        (
            ("Custom", "&kp _COPY"),
            "LEFT",
            "UP",
            "DOWN",
            "RIGHT",
            ("&sk", "LSHFT"),
            ("Custom", "&kp _C(L)"),
            ("Custom", "&select_all"),
            ("Custom", "&select_line"),
            ("Custom", "&select_word"),
        ),
        (
            ("Custom", "&kp _FIND"),
            ("Custom", "&kp _PASTE"),
            ("&kp", ("LS", "TAB")),
            "TAB",
            "&none",
            ("Custom", "&select_none"),
            ("Custom", "&extend_line"),
            ("Custom", "&extend_word"),
            ("Custom", "&kp _PASTE"),
            ("Custom", "&kp _HOME"),
        ),
        (
            "PG_UP",
            "PG_DN",
            ("Custom", "&kp _END"),
            ("Custom", "&kp _C(L)"),
            ("Custom", "&kp _C(K)"),
            ("Custom", "&kp _UNDO"),
            ("Custom", "&kp _REDO"),
            ("Custom", "&kp _FIND_PREV"),
            ("Custom", "&kp _FIND_NEXT"),
            ("Custom", "&tog LAYER_Cursor"),
        ),
        (
            "&none",
            "&none",
            ("Custom", "&select_all"),
            ("Custom", "&select_line"),
            ("Custom", "&select_word"),
            ("Custom", "&kp _FIND"),
            ("Custom", "&kp _FIND_PREV"),
            ("Custom", "&kp _FIND_NEXT"),
            ("Custom", "&kp _C(H)"),
            ("Custom", "&kp _C(K)"),
        ),
    ),
    "Number": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "A",
            "B",
            "C",
            "D",
            "E",
        ),
        (
            "&none",
            "ESC",
            "INS",
            ("&kp", ("LS", "TAB")),
            "DEL",
            "&none",
            "PIPE",
            "HASH",
            "DLLR",
            "CARET",
        ),
        (
            "TILDE",
            "EXCL",
            "E",
            "RET",
            "SPACE",
            "TAB",
            "BSPC",
            "N0",
            ("&kp", ("LS", "G")),
            "N7",
        ),
        (
            "N8",
            "N9",
            "COLON",
            "PRCNT",
            ("&sk", "LSHFT"),
            ("Custom", "&kp LEFT_PINKY_MOD"),
            ("Custom", "&kp LEFT_RINGY_MOD"),
            ("Custom", "&kp LEFT_MIDDY_MOD"),
            ("Custom", "&kp LEFT_INDEX_MOD"),
            "X",
        ),
        (
            "K",
            "N4",
            "N5",
            "N6",
            "MINUS",
            "PLUS",
            "UNDER",
            ("Custom", "&select_all"),
            ("Custom", "&select_line"),
            ("Custom", "&select_word"),
        ),
        (
            ("Custom", "&kp _FIND"),
            "F",
            "&none",
            "&none",
            "&none",
            "LT",
            "GT",
            "COMMA",
            "J",
            "N1",
        ),
        (
            "N2",
            "N3",
            "FSLH",
            "STAR",
            "&none",
            ("Custom", "&kp _UNDO"),
            ("Custom", "&kp _REDO"),
            ("Custom", "&kp _FIND_PREV"),
            ("Custom", "&kp _FIND_NEXT"),
            "&none",
        ),
        (
            ("Custom", "&tog LAYER_Number"),
            "&none",
            "EQUAL",
            "DOT",
            "N0",
            "LPAR",
            "LBKT",
            "RBKT",
            "RPAR",
            "AT",
        ),
    ),
    "Function": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "ESC",
            "INS",
            ("&kp", ("LS", "TAB")),
            "DEL",
            "&none",
            "C_MEDIA_HOME",
            "C_PLAY",
            "C_PREV",
            "C_NEXT",
        ),
        (
            "C_STOP",
            "C_EJECT",
            "&none",
            "RET",
            "SPACE",
            "TAB",
            "BSPC",
            "K_CALC",
            "K_CALC",
            "F7",
        ),
        (
            "F8",
            "F9",
            "F10",
            "F13",
            ("&sk", "LSHFT"),
            ("Custom", "&kp LEFT_PINKY_MOD"),
            ("Custom", "&kp LEFT_RINGY_MOD"),
            ("Custom", "&kp LEFT_MIDDY_MOD"),
            ("Custom", "&kp LEFT_INDEX_MOD"),
            "K_WWW",
        ),
        (
            "K_WWW",
            "F4",
            "F5",
            "F6",
            "F11",
            "F14",
            "&none",
            ("Custom", "&select_all"),
            ("Custom", "&select_line"),
            ("Custom", "&select_word"),
        ),
        (
            ("Custom", "&kp _FIND"),
            ("Custom", "&kp _FILES"),
            ("Custom", "&tog LAYER_Function"),
            "&none",
            "&none",
            "C_PP",
            "C_PREV",
            "C_NEXT",
            ("Custom", "&kp _FILES"),
            "F1",
        ),
        (
            "F2",
            "F3",
            "F12",
            "F15",
            "&none",
            ("Custom", "&kp _UNDO"),
            ("Custom", "&kp _REDO"),
            ("Custom", "&kp _FIND_PREV"),
            ("Custom", "&kp _FIND_NEXT"),
            "&none",
        ),
        (
            "&none",
            "&none",
            "C_MUTE",
            "C_VOL_DN",
            "C_VOL_UP",
            "C_BRI_MAX",
            "C_BRI_UP",
            "C_BRI_DN",
            "C_BRI_MIN",
            "C_BRI_AUTO",
        ),
    ),
    "Emoji": (
        (
            ("Custom", "&emoji_cloudy"),
            ("Custom", "&emoji_mostly_cloudy"),
            ("Custom", "&emoji_partly_cloudy"),
            ("Custom", "&emoji_mostly_sunny"),
            ("Custom", "&emoji_sunny"),
            ("Custom", "&emoji_new_moon"),
            ("Custom", "&emoji_moon_crescent"),
            ("Custom", "&emoji_moon_quarter"),
            ("Custom", "&emoji_moon_gibbous"),
            ("Custom", "&emoji_full_moon"),
        ),
        (
            ("Custom", "&emoji_rainbow "),
            ("Custom", "&emoji_light_skin_tone"),
            ("Custom", "&emoji_medium_light_skin_tone"),
            ("Custom", "&emoji_medium_skin_tone"),
            ("Custom", "&emoji_medium_dark_skin_tone"),
            ("Custom", "&emoji_dark_skin_tone"),
            ("Custom", "&emoji_theme_party"),
            ("Custom", "&emoji_theme_love"),
            ("Custom", "&emoji_theme_nature"),
            ("Custom", "&emoji_theme_strength"),
        ),
        (
            ("Custom", "&emoji_theme_effort"),
            ("Custom", "&emoji_theme_science"),
            ("Custom", "&emoji_left_arrow"),
            ("Custom", "&emoji_bald"),
            ("Custom", "&emoji_red_hair"),
            ("Custom", "&emoji_curly_hair"),
            ("Custom", "&emoji_white_hair"),
            ("Custom", "&emoji_right_arrow"),
            ("Custom", "&emoji_face_laugh"),
            ("Custom", "&emoji_face_smile"),
        ),
        (
            ("Custom", "&emoji_face_eyes"),
            ("Custom", "&emoji_face_joke"),
            ("Custom", "&emoji_face_fear"),
            ("Custom", "&emoji_face_surprise"),
            ("Custom", "&emoji_male_sign"),
            ("Custom", "&emoji_hair_style_preset"),
            ("Custom", "&emoji_skin_tone_preset"),
            ("Custom", "&emoji_gender_sign_preset"),
            ("&sk", "LSHFT"),
            ("Custom", "&emoji_female_sign"),
        ),
        (
            ("Custom", "&emoji_gesture_attention"),
            ("Custom", "&emoji_gesture_approval"),
            ("Custom", "&emoji_gesture_gratitude"),
            ("Custom", "&emoji_gesture_anxiety"),
            ("Custom", "&emoji_gesture_despair"),
            ("Custom", "&emoji_gesture_curious"),
            ("Custom", "&emoji_old_man"),
            ("Custom", "&emoji_man"),
            ("Custom", "&emoji_boy"),
            ("Custom", "&emoji_girl"),
        ),
        (
            ("Custom", "&emoji_woman"),
            ("Custom", "&emoji_old_woman"),
            ("Custom", "&emoji_cityscape"),
            ("Custom", "&emoji_cityscape_dusk"),
            ("Custom", "&emoji_cityscape_night"),
            ("Custom", "&emoji_theme_magic"),
            ("Custom", "&emoji_theme_space"),
            ("Custom", "&emoji_theme_awesome"),
            ("Custom", "&emoji_person_tipping_hand"),
            ("Custom", "&emoji_person_gesturing_ok"),
        ),
        (
            ("Custom", "&emoji_person_bowing"),
            ("Custom", "&emoji_person_raising_hand"),
            ("Custom", "&emoji_person_gesturing_no"),
            ("Custom", "&emoji_theme_sigh"),
            ("Custom", "&emoji_theme_game"),
            ("Custom", "&emoji_theme_trend"),
            ("Custom", "&emoji_baby"),
            ("Custom", "&emoji_baby_bottle"),
            ("Custom", "&tog LAYER_Emoji"),
            ("Custom", "&emoji_zwj"),
        ),
        (
            ("Custom", "&emoji_sunrise"),
            ("Custom", "&emoji_sunrise_mountains"),
            ("Custom", "&emoji_gesture_hands"),
            ("Custom", "&emoji_gesture_point"),
            ("Custom", "&emoji_gesture_thumbs"),
            ("Custom", "&emoji_check"),
            ("Custom", "&emoji_100"),
            ("Custom", "&emoji_warning"),
            ("Custom", "&emoji_cross"),
            ("Custom", "&emoji_question"),
        ),
    ),
    "World": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&world_y_base"),
            ("Custom", "&world_u_base"),
            ("Custom", "&world_o_base"),
            ("Custom", "&world_sign_angle"),
            "&none",
            "&none",
        ),
        (
            ("&sk", "LALT"),
            ("&sk", "RALT"),
            "&none",
            "&none",
            "&none",
            ("Custom", "&world_consonants_base"),
            ("Custom", "&world_i_base"),
            ("Custom", "&world_e_base"),
            ("Custom", "&world_a_base"),
            ("Custom", "&world_sign_exclaim"),
        ),
        (
            "&none",
            ("&sk", "LSHFT"),
            ("&sk", "LCTRL"),
            ("&sk", "RCTRL"),
            ("&sk", "RSHFT"),
            "&none",
            ("Custom", "&world_currency_base"),
            ("Custom", "&world_quotes_left_base"),
            ("Custom", "&world_sign_dash"),
            ("Custom", "&world_sign_landmark"),
        ),
        (
            ("Custom", "&world_sign_ordinal"),
            ("Custom", "&world_sign_question"),
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&world_sign_base"),
            ("Custom", "&world_quotes_right_base"),
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&tog LAYER_World"),
            "&none",
            "&none",
            "&none",
            "&none",
        ),
    ),
    "Symbol": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "GRAVE",
            "LBRC",
            "LBKT",
            "RBKT",
            "RBRC",
            "DOT",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "EXCL",
            "COMMA",
            "LPAR",
            "RPAR",
            "SEMI",
            "QMARK",
            "GRAVE",
            ("Custom", "&sk RIGHT_INDEX_MOD"),
        ),
        (
            ("Custom", "&sk RIGHT_MIDDY_MOD"),
            ("Custom", "&sk RIGHT_RINGY_MOD"),
            ("Custom", "&sk RIGHT_PINKY_MOD"),
            "&none",
            "HASH",
            "CARET",
            "EQUAL",
            "UNDER",
            "DLLR",
            "STAR",
        ),
        (
            "DQT",
            "BSPC",
            "TAB",
            "SPACE",
            "RET",
            "&none",
            "TILDE",
            "LT",
            "PIPE",
            "MINUS",
        ),
        (
            "GT",
            "FSLH",
            "BSLH",
            "DOT",
            "STAR",
            "&none",
            "&none",
            "&none",
            "SQT",
            "DEL",
        ),
        (
            ("&kp", ("LS", "TAB")),
            "INS",
            "ESC",
            "&none",
            ("Custom", "&dot_dot"),
            "AMPS",
            "SQT",
            "DQT",
            "PLUS",
            "PRCNT",
        ),
        (
            "COLON",
            "AT",
            "&none",
            "&none",
            ("Custom", "&tog LAYER_Symbol"),
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
    ),
    "System": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "PSCRN",
            "PAUSE_BREAK",
            ("&rgb_ug", "RGB_TOG"),
            ("&rgb_ug", "RGB_TOG"),
            ("Custom", "&sk RIGHT_INDEX_MOD"),
        ),
        (
            ("Custom", "&sk RIGHT_MIDDY_MOD"),
            ("Custom", "&sk RIGHT_RINGY_MOD"),
            ("Custom", "&sk RIGHT_PINKY_MOD"),
            "&none",
            "&none",
            ("&rgb_ug", "RGB_SPI"),
            ("&rgb_ug", "RGB_SAI"),
            ("&rgb_ug", "RGB_HUI"),
            ("&rgb_ug", "RGB_BRI"),
            ("&rgb_ug", "RGB_EFF"),
        ),
        (
            ("&rgb_ug", "RGB_EFF"),
            ("&rgb_ug", "RGB_BRI"),
            ("&rgb_ug", "RGB_HUI"),
            ("&rgb_ug", "RGB_SAI"),
            ("&rgb_ug", "RGB_SPI"),
            ("Custom", "&kp _LOCK"),
            "&none",
            ("&rgb_ug", "RGB_SPD"),
            ("&rgb_ug", "RGB_SAD"),
            ("&rgb_ug", "RGB_HUD"),
        ),
        (
            ("&rgb_ug", "RGB_BRD"),
            ("&rgb_ug", "RGB_EFR"),
            ("Custom", "&kp _LOCK"),
            ("Custom", "&kp _SLEEP"),
            ("Custom", "&kp _POWER"),
            "&none",
            "&none",
            ("Custom", "&tog LAYER_System"),
            ("&rgb_ug", "RGB_EFR"),
            ("&rgb_ug", "RGB_BRD"),
        ),
        (
            ("&rgb_ug", "RGB_HUD"),
            ("&rgb_ug", "RGB_SAD"),
            ("&rgb_ug", "RGB_SPD"),
            ("Custom", "&kp _SLEEP"),
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&linux_magic_sysrq"),
            "SLCK",
        ),
        (
            "KP_NUM",
            "CAPS",
            "&none",
            "PSCRN",
            "PAUSE_BREAK",
            ("Custom", "&linux_magic_sysrq"),
            "SLCK",
            "KP_NUM",
            "CAPS",
            ("Custom", "&kp _POWER"),
        ),
    ),
    "Mouse": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&msc MOUSE_SCROLL_LEFT"),
            ("&mmv", "MOVE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_RIGHT"),
            "&none",
            "&none",
            ("Custom", "&sk RIGHT_INDEX_MOD"),
        ),
        (
            ("Custom", "&sk RIGHT_MIDDY_MOD"),
            ("Custom", "&sk RIGHT_RINGY_MOD"),
            ("Custom", "&sk RIGHT_PINKY_MOD"),
            "K_APP",
            "&none",
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("&mmv", "MOVE_LEFT"),
            ("&mmv", "MOVE_DOWN"),
            ("&mmv", "MOVE_RIGHT"),
            ("Custom", "&msc MOUSE_SCROLL_UP"),
        ),
        (
            ("Custom", "&msc MOUSE_SCROLL_UP"),
            ("Custom", "&mo LAYER_MouseFast"),
            ("Custom", "&mo LAYER_MouseSlow"),
            ("Custom", "&mo LAYER_MouseFine"),
            ("Custom", "&mo LAYER_MouseWarp"),
            ("&mkp", "MB4"),
            "&none",
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            ("Custom", "&kp _CUT"),
            ("Custom", "&kp _COPY"),
        ),
        (
            ("Custom", "&kp _PASTE"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            ("&mkp", "MCLK"),
            "K_APP",
            ("&mkp", "MB5"),
            ("Custom", "&kp _PASTE"),
            ("Custom", "&kp _COPY"),
            ("Custom", "&kp _PASTE"),
            ("Custom", "&msc MOUSE_SCROLL_DOWN"),
            ("Custom", "&msc MOUSE_SCROLL_LEFT"),
        ),
        (
            ("&mmv", "MOVE_UP"),
            ("Custom", "&msc MOUSE_SCROLL_RIGHT"),
            ("&mkp", "LCLK"),
            ("&mkp", "MB5"),
            "&none",
            ("Custom", "&mo LAYER_MouseWarp"),
            ("Custom", "&mo LAYER_MouseFine"),
            ("Custom", "&mo LAYER_MouseSlow"),
            ("Custom", "&mo LAYER_MouseFast"),
            ("&mkp", "LCLK"),
        ),
        (
            ("&mkp", "RCLK"),
            ("&mkp", "MB4"),
            "&none",
            ("Custom", "&tog LAYER_Mouse"),
            "&none",
            ("&mmv", "MOVE_LEFT"),
            ("&mmv", "MOVE_DOWN"),
            ("&mmv", "MOVE_RIGHT"),
            ("&mkp", "RCLK"),
            ("&mkp", "MCLK"),
        ),
    ),
    "MouseFine": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "MouseSlow": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "MouseFast": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "MouseWarp": (
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
        (
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
            "&trans",
        ),
    ),
    "Gaming": (
        (
            "ESC",
            "P",
            "O",
            "N",
            "BSPC",
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
        ),
        (
            "M",
            "N6",
            "N7",
            "N8",
            "N9",
            "N0",
            "F6",
            "F7",
            "F8",
            "F9",
        ),
        (
            "F10",
            "F11",
            "I",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "Y",
            "U",
        ),
        (
            "I",
            "O",
            "P",
            "F12",
            "T",
            "TAB",
            "Q",
            "W",
            "E",
            "R",
        ),
        (
            "H",
            "J",
            "K",
            "L",
            "SEMI",
            "SQT",
            "G",
            "LSHFT",
            "A",
            "S",
        ),
        (
            "D",
            "F",
            "LSHFT",
            "LALT",
            "V",
            "ESC",
            "UP",
            "RET",
            "N",
            "M",
        ),
        (
            "COMMA",
            "DOT",
            "FSLH",
            "BSLH",
            "B",
            "LCTRL",
            "Z",
            "X",
            "C",
            "SPACE",
        ),
        (
            "LCTRL",
            "RET",
            "LEFT",
            "DOWN",
            "RIGHT",
            "MINUS",
            "LBKT",
            "RBKT",
            "EQUAL",
            "GRAVE",
        ),
    ),
    "Factory": (
        (
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "F7",
            "F8",
            "F9",
            "F10",
        ),
        (
            "EQUAL",
            "N1",
            "N2",
            "N3",
            "N4",
            "N5",
            "N6",
            "N7",
            "N8",
            "N9",
        ),
        (
            "N0",
            "MINUS",
            "TAB",
            "Q",
            "W",
            "E",
            "R",
            "T",
            "Y",
            "U",
        ),
        (
            "I",
            "O",
            "P",
            "BSLH",
            "ESC",
            "A",
            "S",
            "D",
            "F",
            "G",
        ),
        (
            "H",
            "J",
            "K",
            "L",
            "SEMI",
            "SQT",
            "GRAVE",
            "Z",
            "X",
            "C",
        ),
        (
            "V",
            "B",
            "LSHFT",
            "LCTRL",
            "&lower",
            "LGUI",
            "RCTRL",
            "RSHFT",
            "N",
            "M",
        ),
        (
            "COMMA",
            "DOT",
            "FSLH",
            "PG_UP",
            "&magic",
            "HOME",
            "END",
            "LEFT",
            "RIGHT",
            "BSPC",
        ),
        (
            "DEL",
            "LALT",
            "RALT",
            "RET",
            "SPACE",
            "UP",
            "DOWN",
            "LBKT",
            "RBKT",
            "PG_DN",
        ),
    ),
    "Lower": (
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "KP_NUM",
            "KP_SLASH",
            "KP_MULTIPLY",
            "KP_MINUS",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "KP_CLEAR",
            "KP_N7",
            "KP_N8",
            "KP_N9",
        ),
        (
            "KP_MINUS",
            "FSLH",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "KP_LPAR",
            "KP_N4",
        ),
        (
            "KP_N5",
            "KP_N6",
            "KP_PLUS",
            "KP_MULTIPLY",
            "RALT",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "KP_RPAR",
            "KP_N1",
            "KP_N2",
            "KP_N3",
            "KP_ENTER",
            "KP_EQUAL",
            "&trans",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            ("Custom", "&tog LAYER_Function"),
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&tog LAYER_System"),
            "KP_N0",
            "KP_N0",
        ),
        (
            "KP_COMMA",
            "KP_DOT",
            "KP_ENTER",
            "&trans",
            "&none",
            "&none",
            "&none",
            "&none",
            ("Custom", "&tog LAYER_Emoji"),
            ("Custom", "&tog LAYER_Cursor"),
        ),
        (
            ("Custom", "&tog LAYER_Number"),
            "&none",
            "&none",
            ("Custom", "&tog LAYER_Mouse"),
            ("Custom", "&tog LAYER_Symbol"),
            ("Custom", "&tog LAYER_World"),
            "&none",
            "&none",
            "&none",
            "&none",
        ),
    ),
    "Magic": (
        (
            ("&bt", "BT_CLR"),
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            ("&bt", "BT_CLR_ALL"),
        ),
        (
            ("Custom", "&to 0"),
            ("Custom", "&to 1"),
            ("Custom", "&to 2"),
            ("Custom", "&to 3"),
            ("Custom", "&to 4"),
            ("Custom", "&to 5"),
            ("Custom", "&to 6"),
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            ("&rgb_ug", "RGB_SPI"),
            ("&rgb_ug", "RGB_SAI"),
            ("&rgb_ug", "RGB_HUI"),
            ("&rgb_ug", "RGB_BRI"),
            ("&rgb_ug", "RGB_TOG"),
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&bootloader",
            ("&rgb_ug", "RGB_SPD"),
            ("&rgb_ug", "RGB_SAD"),
            ("&rgb_ug", "RGB_HUD"),
            ("&rgb_ug", "RGB_BRD"),
            ("&rgb_ug", "RGB_EFF"),
        ),
        (
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&bootloader",
            "&reset",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&bt_2",
            "&bt_3",
            ("&tog", 29),
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
        (
            "&none",
            "&none",
            "&none",
            "&reset",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&bt_0",
        ),
        (
            "&bt_1",
            ("&out", "OUT_USB"),
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
            "&none",
        ),
    ),
}
