"""Finger Layers rows for Glorious Engrammer."""

from __future__ import annotations

from typing import Dict, Tuple

from glove80.base import LayerSpec
from glove80.layouts.layers import Token, _rows_to_layer_spec

LayerRows = Tuple[Tuple[Token, ...], ...]


def _layer(rows: LayerRows) -> LayerSpec:
    return _rows_to_layer_spec(rows)


FINGER_LAYER_SPECS: Dict[str, LayerSpec] = {
    "LeftPinky": _layer(
        (
            (
                ("Custom", "&left_pinky_tap KEY_LH_C6R1"),
                ("Custom", "&left_pinky_tap KEY_LH_C5R1"),
                ("Custom", "&left_pinky_tap KEY_LH_C4R1"),
                ("Custom", "&left_pinky_tap KEY_LH_C3R1"),
                ("Custom", "&left_pinky_tap KEY_LH_C2R1"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                ("Custom", "&left_pinky_tap KEY_LH_C6R2"),
                ("Custom", "&left_pinky_tap KEY_LH_C5R2"),
                ("Custom", "&left_pinky_tap KEY_LH_C4R2"),
                ("Custom", "&left_pinky_tap KEY_LH_C3R2"),
                ("Custom", "&left_pinky_tap KEY_LH_C2R2"),
                ("Custom", "&left_pinky_tap KEY_LH_C1R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&left_pinky_tap KEY_LH_C6R3"),
                ("Custom", "&left_pinky_tap KEY_LH_C5R3"),
                ("Custom", "&left_pinky_tap KEY_LH_C4R3"),
                ("Custom", "&left_pinky_tap KEY_LH_C3R3"),
                ("Custom", "&left_pinky_tap KEY_LH_C2R3"),
                ("Custom", "&left_pinky_tap KEY_LH_C1R3"),
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_pinky_tap KEY_LH_C6R4"),
                "&none",
                ("Custom", "&LeftPinkyRingy"),
                ("Custom", "&LeftPinkyMiddy"),
                ("Custom", "&LeftPinkyIndex"),
                ("Custom", "&left_pinky_tap KEY_LH_C1R4"),
            ),
            (
                "&trans",
                ("Custom", "&kp RIGHT_INDEX_KEY"),
                ("Custom", "&kp RIGHT_MIDDY_KEY"),
                ("Custom", "&kp RIGHT_RINGY_KEY"),
                ("Custom", "&kp RIGHT_PINKY_KEY"),
                "&trans",
                "&trans",
                ("Custom", "&left_pinky_tap KEY_LH_C5R5"),
                ("Custom", "&left_pinky_tap KEY_LH_C4R5"),
                ("Custom", "&left_pinky_tap KEY_LH_C3R5"),
            ),
            (
                ("Custom", "&left_pinky_tap KEY_LH_C2R5"),
                ("Custom", "&left_pinky_tap KEY_LH_C1R5"),
                ("Custom", "&mo LAY_LH_T1"),
                ("Custom", "&left_pinky_tap KEY_LH_T2"),
                ("Custom", "&left_pinky_tap KEY_LH_T3"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_pinky_tap KEY_LH_C5R6"),
                ("Custom", "&left_pinky_tap KEY_LH_C4R6"),
                ("Custom", "&left_pinky_tap KEY_LH_C3R6"),
                ("Custom", "&mo LAY_LH_C2R6"),
                ("Custom", "&mo LAY_LH_T4"),
            ),
            (
                ("Custom", "&mo LAY_LH_T5"),
                ("Custom", "&mo LAY_LH_T6"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
        )
    ),
    "LeftRingy": _layer(
        (
            (
                ("Custom", "&left_ringy_tap KEY_LH_C6R1"),
                ("Custom", "&left_ringy_tap KEY_LH_C5R1"),
                ("Custom", "&left_ringy_tap KEY_LH_C4R1"),
                ("Custom", "&left_ringy_tap KEY_LH_C3R1"),
                ("Custom", "&left_ringy_tap KEY_LH_C2R1"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                ("Custom", "&left_ringy_tap KEY_LH_C6R2"),
                ("Custom", "&left_ringy_tap KEY_LH_C5R2"),
                ("Custom", "&left_ringy_tap KEY_LH_C4R2"),
                ("Custom", "&left_ringy_tap KEY_LH_C3R2"),
                ("Custom", "&left_ringy_tap KEY_LH_C2R2"),
                ("Custom", "&left_ringy_tap KEY_LH_C1R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&left_ringy_tap KEY_LH_C6R3"),
                ("Custom", "&left_ringy_tap KEY_LH_C5R3"),
                ("Custom", "&left_ringy_tap KEY_LH_C4R3"),
                ("Custom", "&left_ringy_tap KEY_LH_C3R3"),
                ("Custom", "&left_ringy_tap KEY_LH_C2R3"),
                ("Custom", "&left_ringy_tap KEY_LH_C1R3"),
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_ringy_tap KEY_LH_C6R4"),
                ("Custom", "&LeftRingyPinky"),
                "&none",
                ("Custom", "&LeftRingyMiddy"),
                ("Custom", "&LeftRingyIndex"),
                ("Custom", "&left_ringy_tap KEY_LH_C1R4"),
            ),
            (
                "&trans",
                ("Custom", "&kp RIGHT_INDEX_KEY"),
                ("Custom", "&kp RIGHT_MIDDY_KEY"),
                ("Custom", "&kp RIGHT_RINGY_KEY"),
                ("Custom", "&kp RIGHT_PINKY_KEY"),
                "&trans",
                "&trans",
                ("Custom", "&left_ringy_tap KEY_LH_C5R5"),
                ("Custom", "&left_ringy_tap KEY_LH_C4R5"),
                ("Custom", "&left_ringy_tap KEY_LH_C3R5"),
            ),
            (
                ("Custom", "&left_ringy_tap KEY_LH_C2R5"),
                ("Custom", "&left_ringy_tap KEY_LH_C1R5"),
                ("Custom", "&mo LAY_LH_T1"),
                ("Custom", "&left_ringy_tap KEY_LH_T2"),
                ("Custom", "&left_ringy_tap KEY_LH_T3"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_ringy_tap KEY_LH_C5R6"),
                ("Custom", "&left_ringy_tap KEY_LH_C4R6"),
                ("Custom", "&left_ringy_tap KEY_LH_C3R6"),
                ("Custom", "&mo LAY_LH_C2R6"),
                ("Custom", "&mo LAY_LH_T4"),
            ),
            (
                ("Custom", "&mo LAY_LH_T5"),
                ("Custom", "&mo LAY_LH_T6"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
        )
    ),
    "LeftMiddy": _layer(
        (
            (
                ("Custom", "&left_middy_tap KEY_LH_C6R1"),
                ("Custom", "&left_middy_tap KEY_LH_C5R1"),
                ("Custom", "&left_middy_tap KEY_LH_C4R1"),
                ("Custom", "&left_middy_tap KEY_LH_C3R1"),
                ("Custom", "&left_middy_tap KEY_LH_C2R1"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                ("Custom", "&left_middy_tap KEY_LH_C6R2"),
                ("Custom", "&left_middy_tap KEY_LH_C5R2"),
                ("Custom", "&left_middy_tap KEY_LH_C4R2"),
                ("Custom", "&left_middy_tap KEY_LH_C3R2"),
                ("Custom", "&left_middy_tap KEY_LH_C2R2"),
                ("Custom", "&left_middy_tap KEY_LH_C1R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&left_middy_tap KEY_LH_C6R3"),
                ("Custom", "&left_middy_tap KEY_LH_C5R3"),
                ("Custom", "&left_middy_tap KEY_LH_C4R3"),
                ("Custom", "&left_middy_tap KEY_LH_C3R3"),
                ("Custom", "&left_middy_tap KEY_LH_C2R3"),
                ("Custom", "&left_middy_tap KEY_LH_C1R3"),
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_middy_tap KEY_LH_C6R4"),
                ("Custom", "&LeftMiddyPinky"),
                ("Custom", "&LeftMiddyRingy"),
                "&none",
                ("Custom", "&LeftMiddyIndex"),
                ("Custom", "&left_middy_tap KEY_LH_C1R4"),
            ),
            (
                "&trans",
                ("Custom", "&kp RIGHT_INDEX_KEY"),
                ("Custom", "&kp RIGHT_MIDDY_KEY"),
                ("Custom", "&kp RIGHT_RINGY_KEY"),
                ("Custom", "&kp RIGHT_PINKY_KEY"),
                "&trans",
                "&trans",
                ("Custom", "&left_middy_tap KEY_LH_C5R5"),
                ("Custom", "&left_middy_tap KEY_LH_C4R5"),
                ("Custom", "&left_middy_tap KEY_LH_C3R5"),
            ),
            (
                ("Custom", "&left_middy_tap KEY_LH_C2R5"),
                ("Custom", "&left_middy_tap KEY_LH_C1R5"),
                ("Custom", "&mo LAY_LH_T1"),
                ("Custom", "&left_middy_tap KEY_LH_T2"),
                ("Custom", "&left_middy_tap KEY_LH_T3"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_middy_tap KEY_LH_C5R6"),
                ("Custom", "&left_middy_tap KEY_LH_C4R6"),
                ("Custom", "&left_middy_tap KEY_LH_C3R6"),
                ("Custom", "&mo LAY_LH_C2R6"),
                ("Custom", "&mo LAY_LH_T4"),
            ),
            (
                ("Custom", "&mo LAY_LH_T5"),
                ("Custom", "&mo LAY_LH_T6"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
        )
    ),
    "LeftIndex": _layer(
        (
            (
                ("Custom", "&left_index_tap KEY_LH_C6R1"),
                ("Custom", "&left_index_tap KEY_LH_C5R1"),
                ("Custom", "&left_index_tap KEY_LH_C4R1"),
                ("Custom", "&left_index_tap KEY_LH_C3R1"),
                ("Custom", "&left_index_tap KEY_LH_C2R1"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                ("Custom", "&left_index_tap KEY_LH_C6R2"),
                ("Custom", "&left_index_tap KEY_LH_C5R2"),
                ("Custom", "&left_index_tap KEY_LH_C4R2"),
                ("Custom", "&left_index_tap KEY_LH_C3R2"),
                ("Custom", "&left_index_tap KEY_LH_C2R2"),
                ("Custom", "&left_index_tap KEY_LH_C1R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&left_index_tap KEY_LH_C6R3"),
                ("Custom", "&left_index_tap KEY_LH_C5R3"),
                ("Custom", "&left_index_tap KEY_LH_C4R3"),
                ("Custom", "&left_index_tap KEY_LH_C3R3"),
                ("Custom", "&left_index_tap KEY_LH_C2R3"),
                ("Custom", "&left_index_tap KEY_LH_C1R3"),
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_index_tap KEY_LH_C6R4"),
                ("Custom", "&LeftIndexPinky"),
                ("Custom", "&LeftIndexRingy"),
                ("Custom", "&LeftIndexMiddy"),
                "&none",
                ("Custom", "&left_index_tap KEY_LH_C1R4"),
            ),
            (
                "&trans",
                ("Custom", "&kp RIGHT_INDEX_KEY"),
                ("Custom", "&kp RIGHT_MIDDY_KEY"),
                ("Custom", "&kp RIGHT_RINGY_KEY"),
                ("Custom", "&kp RIGHT_PINKY_KEY"),
                "&trans",
                "&trans",
                ("Custom", "&left_index_tap KEY_LH_C5R5"),
                ("Custom", "&left_index_tap KEY_LH_C4R5"),
                ("Custom", "&left_index_tap KEY_LH_C3R5"),
            ),
            (
                ("Custom", "&left_index_tap KEY_LH_C2R5"),
                ("Custom", "&left_index_tap KEY_LH_C1R5"),
                ("Custom", "&mo LAY_LH_T1"),
                ("Custom", "&left_index_tap KEY_LH_T2"),
                ("Custom", "&left_index_tap KEY_LH_T3"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&left_index_tap KEY_LH_C5R6"),
                ("Custom", "&left_index_tap KEY_LH_C4R6"),
                ("Custom", "&left_index_tap KEY_LH_C3R6"),
                ("Custom", "&mo LAY_LH_C2R6"),
                ("Custom", "&mo LAY_LH_T4"),
            ),
            (
                ("Custom", "&mo LAY_LH_T5"),
                ("Custom", "&mo LAY_LH_T6"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
        )
    ),
    "RightPinky": _layer(
        (
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_pinky_tap KEY_RH_C2R1"),
                ("Custom", "&right_pinky_tap KEY_RH_C3R1"),
                ("Custom", "&right_pinky_tap KEY_RH_C4R1"),
                ("Custom", "&right_pinky_tap KEY_RH_C5R1"),
                ("Custom", "&right_pinky_tap KEY_RH_C6R1"),
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_pinky_tap KEY_RH_C1R2"),
                ("Custom", "&right_pinky_tap KEY_RH_C2R2"),
                ("Custom", "&right_pinky_tap KEY_RH_C3R2"),
                ("Custom", "&right_pinky_tap KEY_RH_C4R2"),
            ),
            (
                ("Custom", "&right_pinky_tap KEY_RH_C5R2"),
                ("Custom", "&right_pinky_tap KEY_RH_C6R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_pinky_tap KEY_RH_C1R3"),
                ("Custom", "&right_pinky_tap KEY_RH_C2R3"),
            ),
            (
                ("Custom", "&right_pinky_tap KEY_RH_C3R3"),
                ("Custom", "&right_pinky_tap KEY_RH_C4R3"),
                ("Custom", "&right_pinky_tap KEY_RH_C5R3"),
                ("Custom", "&right_pinky_tap KEY_RH_C6R3"),
                "&trans",
                ("Custom", "&kp LEFT_PINKY_KEY"),
                ("Custom", "&kp LEFT_RINGY_KEY"),
                ("Custom", "&kp LEFT_MIDDY_KEY"),
                ("Custom", "&kp LEFT_INDEX_KEY"),
                "&trans",
            ),
            (
                ("Custom", "&right_pinky_tap KEY_RH_C1R4"),
                ("Custom", "&RightPinkyIndex"),
                ("Custom", "&RightPinkyMiddy"),
                ("Custom", "&RightPinkyRingy"),
                "&none",
                ("Custom", "&right_pinky_tap KEY_RH_C6R4"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_pinky_tap KEY_RH_T3"),
                ("Custom", "&right_pinky_tap KEY_RH_T2"),
                ("Custom", "&mo LAY_RH_T1"),
                ("Custom", "&right_pinky_tap KEY_RH_C1R5"),
                ("Custom", "&right_pinky_tap KEY_RH_C2R5"),
            ),
            (
                ("Custom", "&right_pinky_tap KEY_RH_C3R5"),
                ("Custom", "&right_pinky_tap KEY_RH_C4R5"),
                ("Custom", "&right_pinky_tap KEY_RH_C5R5"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&mo LAY_RH_T6"),
                ("Custom", "&mo LAY_RH_T5"),
                ("Custom", "&mo LAY_RH_T4"),
                ("Custom", "&mo LAY_RH_C2R6"),
                ("Custom", "&right_pinky_tap KEY_RH_C3R6"),
                ("Custom", "&right_pinky_tap KEY_RH_C4R6"),
                ("Custom", "&right_pinky_tap KEY_RH_C5R6"),
                "&trans",
            ),
        )
    ),
    "RightRingy": _layer(
        (
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_ringy_tap KEY_RH_C2R1"),
                ("Custom", "&right_ringy_tap KEY_RH_C3R1"),
                ("Custom", "&right_ringy_tap KEY_RH_C4R1"),
                ("Custom", "&right_ringy_tap KEY_RH_C5R1"),
                ("Custom", "&right_ringy_tap KEY_RH_C6R1"),
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_ringy_tap KEY_RH_C1R2"),
                ("Custom", "&right_ringy_tap KEY_RH_C2R2"),
                ("Custom", "&right_ringy_tap KEY_RH_C3R2"),
                ("Custom", "&right_ringy_tap KEY_RH_C4R2"),
            ),
            (
                ("Custom", "&right_ringy_tap KEY_RH_C5R2"),
                ("Custom", "&right_ringy_tap KEY_RH_C6R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_ringy_tap KEY_RH_C1R3"),
                ("Custom", "&right_ringy_tap KEY_RH_C2R3"),
            ),
            (
                ("Custom", "&right_ringy_tap KEY_RH_C3R3"),
                ("Custom", "&right_ringy_tap KEY_RH_C4R3"),
                ("Custom", "&right_ringy_tap KEY_RH_C5R3"),
                ("Custom", "&right_ringy_tap KEY_RH_C6R3"),
                "&trans",
                ("Custom", "&kp LEFT_PINKY_KEY"),
                ("Custom", "&kp LEFT_RINGY_KEY"),
                ("Custom", "&kp LEFT_MIDDY_KEY"),
                ("Custom", "&kp LEFT_INDEX_KEY"),
                "&trans",
            ),
            (
                ("Custom", "&right_ringy_tap KEY_RH_C1R4"),
                ("Custom", "&RightRingyIndex"),
                ("Custom", "&RightRingyMiddy"),
                "&none",
                ("Custom", "&RightRingyPinky"),
                ("Custom", "&right_ringy_tap KEY_RH_C6R4"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_ringy_tap KEY_RH_T3"),
                ("Custom", "&right_ringy_tap KEY_RH_T2"),
                ("Custom", "&mo LAY_RH_T1"),
                ("Custom", "&right_ringy_tap KEY_RH_C1R5"),
                ("Custom", "&right_ringy_tap KEY_RH_C2R5"),
            ),
            (
                ("Custom", "&right_ringy_tap KEY_RH_C3R5"),
                ("Custom", "&right_ringy_tap KEY_RH_C4R5"),
                ("Custom", "&right_ringy_tap KEY_RH_C5R5"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&mo LAY_RH_T6"),
                ("Custom", "&mo LAY_RH_T5"),
                ("Custom", "&mo LAY_RH_T4"),
                ("Custom", "&mo LAY_RH_C2R6"),
                ("Custom", "&right_ringy_tap KEY_RH_C3R6"),
                ("Custom", "&right_ringy_tap KEY_RH_C4R6"),
                ("Custom", "&right_ringy_tap KEY_RH_C5R6"),
                "&trans",
            ),
        )
    ),
    "RightMiddy": _layer(
        (
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_middy_tap KEY_RH_C2R1"),
                ("Custom", "&right_middy_tap KEY_RH_C3R1"),
                ("Custom", "&right_middy_tap KEY_RH_C4R1"),
                ("Custom", "&right_middy_tap KEY_RH_C5R1"),
                ("Custom", "&right_middy_tap KEY_RH_C6R1"),
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_middy_tap KEY_RH_C1R2"),
                ("Custom", "&right_middy_tap KEY_RH_C2R2"),
                ("Custom", "&right_middy_tap KEY_RH_C3R2"),
                ("Custom", "&right_middy_tap KEY_RH_C4R2"),
            ),
            (
                ("Custom", "&right_middy_tap KEY_RH_C5R2"),
                ("Custom", "&right_middy_tap KEY_RH_C6R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_middy_tap KEY_RH_C1R3"),
                ("Custom", "&right_middy_tap KEY_RH_C2R3"),
            ),
            (
                ("Custom", "&right_middy_tap KEY_RH_C3R3"),
                ("Custom", "&right_middy_tap KEY_RH_C4R3"),
                ("Custom", "&right_middy_tap KEY_RH_C5R3"),
                ("Custom", "&right_middy_tap KEY_RH_C6R3"),
                "&trans",
                ("Custom", "&kp LEFT_PINKY_KEY"),
                ("Custom", "&kp LEFT_RINGY_KEY"),
                ("Custom", "&kp LEFT_MIDDY_KEY"),
                ("Custom", "&kp LEFT_INDEX_KEY"),
                "&trans",
            ),
            (
                ("Custom", "&right_middy_tap KEY_RH_C1R4"),
                ("Custom", "&RightMiddyIndex"),
                "&none",
                ("Custom", "&RightMiddyRingy"),
                ("Custom", "&RightMiddyPinky"),
                ("Custom", "&right_middy_tap KEY_RH_C6R4"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_middy_tap KEY_RH_T3"),
                ("Custom", "&right_middy_tap KEY_RH_T2"),
                ("Custom", "&mo LAY_RH_T1"),
                ("Custom", "&right_middy_tap KEY_RH_C1R5"),
                ("Custom", "&right_middy_tap KEY_RH_C2R5"),
            ),
            (
                ("Custom", "&right_middy_tap KEY_RH_C3R5"),
                ("Custom", "&right_middy_tap KEY_RH_C4R5"),
                ("Custom", "&right_middy_tap KEY_RH_C5R5"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&mo LAY_RH_T6"),
                ("Custom", "&mo LAY_RH_T5"),
                ("Custom", "&mo LAY_RH_T4"),
                ("Custom", "&mo LAY_RH_C2R6"),
                ("Custom", "&right_middy_tap KEY_RH_C3R6"),
                ("Custom", "&right_middy_tap KEY_RH_C4R6"),
                ("Custom", "&right_middy_tap KEY_RH_C5R6"),
                "&trans",
            ),
        )
    ),
    "RightIndex": _layer(
        (
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_index_tap KEY_RH_C2R1"),
                ("Custom", "&right_index_tap KEY_RH_C3R1"),
                ("Custom", "&right_index_tap KEY_RH_C4R1"),
                ("Custom", "&right_index_tap KEY_RH_C5R1"),
                ("Custom", "&right_index_tap KEY_RH_C6R1"),
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_index_tap KEY_RH_C1R2"),
                ("Custom", "&right_index_tap KEY_RH_C2R2"),
                ("Custom", "&right_index_tap KEY_RH_C3R2"),
                ("Custom", "&right_index_tap KEY_RH_C4R2"),
            ),
            (
                ("Custom", "&right_index_tap KEY_RH_C5R2"),
                ("Custom", "&right_index_tap KEY_RH_C6R2"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_index_tap KEY_RH_C1R3"),
                ("Custom", "&right_index_tap KEY_RH_C2R3"),
            ),
            (
                ("Custom", "&right_index_tap KEY_RH_C3R3"),
                ("Custom", "&right_index_tap KEY_RH_C4R3"),
                ("Custom", "&right_index_tap KEY_RH_C5R3"),
                ("Custom", "&right_index_tap KEY_RH_C6R3"),
                "&trans",
                ("Custom", "&kp LEFT_PINKY_KEY"),
                ("Custom", "&kp LEFT_RINGY_KEY"),
                ("Custom", "&kp LEFT_MIDDY_KEY"),
                ("Custom", "&kp LEFT_INDEX_KEY"),
                "&trans",
            ),
            (
                ("Custom", "&right_index_tap KEY_RH_C1R4"),
                "&none",
                ("Custom", "&RightIndexMiddy"),
                ("Custom", "&RightIndexRingy"),
                ("Custom", "&RightIndexPinky"),
                ("Custom", "&right_index_tap KEY_RH_C6R4"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                ("Custom", "&right_index_tap KEY_RH_T3"),
                ("Custom", "&right_index_tap KEY_RH_T2"),
                ("Custom", "&mo LAY_RH_T1"),
                ("Custom", "&right_index_tap KEY_RH_C1R5"),
                ("Custom", "&right_index_tap KEY_RH_C2R5"),
            ),
            (
                ("Custom", "&right_index_tap KEY_RH_C3R5"),
                ("Custom", "&right_index_tap KEY_RH_C4R5"),
                ("Custom", "&right_index_tap KEY_RH_C5R5"),
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
                "&trans",
            ),
            (
                "&trans",
                "&trans",
                ("Custom", "&mo LAY_RH_T6"),
                ("Custom", "&mo LAY_RH_T5"),
                ("Custom", "&mo LAY_RH_T4"),
                ("Custom", "&mo LAY_RH_C2R6"),
                ("Custom", "&right_index_tap KEY_RH_C3R6"),
                ("Custom", "&right_index_tap KEY_RH_C4R6"),
                ("Custom", "&right_index_tap KEY_RH_C5R6"),
                "&trans",
            ),
        )
    ),
}
